# Python -断言语句

> 原文:[https://www.tutorialsteacher.com/python/python-assert](https://www.tutorialsteacher.com/python/python-assert)

在 Python 中，如果给定条件评估为真，则使用`assert`语句继续执行。 如果断言条件评估为假，那么它会引发带有指定错误消息的`AssertionError`异常。

### 句法

```
assert condition [, Error Message] 
```

下面的示例演示了一个简单的 assert 语句。

Example: assert<button class="copy-btn pull-right" title="Copy example code">*Copy*</button> *```
x = 10
assert x > 0
print('x is a positive number.') 
```

Output

```
x is a positive number. 
```

在上面的例子中，断言条件`x > 0`评估为真，因此它将继续执行下一条语句，没有任何错误。

assert 语句可以选择性地包含一个错误消息字符串，该字符串与`AssertionError`一起显示。 考虑以下带有错误消息的断言语句。

Example: Assert Statement with Error Message<button class="copy-btn pull-right" title="Copy example code">*Copy*</button> *```
x = 0
assert x > 0, 'Only positive numbers are allowed'
print('x is a positive number.') 
```

Output

```
Traceback (most recent call last):
    assert x > 0, 'Only positive numbers are allowed'
AssertionError: Only positive numbers are allowed 
```

以上，`x=0`，所以断言条件`x > 0`变为假，所以它会用指定的消息“只允许正数”来引发`AssertionError`。 不执行`print('x is a positive number.')`语句。

下面的示例在函数中使用了 assert 语句。

Example: assert<button class="copy-btn pull-right" title="Copy example code">*Copy*</button> *```
def square(x):
    assert x>=0, 'Only positive numbers are allowed'
    return x*x

n = square(2) # returns 4
n = square(-2) # raise an AssertionError 
```

Output

```
Traceback (most recent call last):
    assert x > 0, 'Only positive numbers are allowed'
AssertionError: Only positive numbers are allowed 
```

上图中，`square(2)`将返回 4，而`square(-2)`将加注一个`AssertionError`，因为我们通过了-2。

`AssertionError`也是一个内置的异常，可以使用 [try 来处理-除了如下所示的](/python/exception-handling-in-python)构造:

Example: AssertionError<button class="copy-btn pull-right" title="Copy example code">*Copy*</button> *```
def square(x):
    assert x>=0, 'Only positive numbers are allowed'
    return x*x

try:
    square(-2)
except AssertionError as msg:
    print(msg) 
```

Output

```
Only positive numbers are allowed 
```

上图，调用`square(-2)`会引发`AssertionError`，由除块处理。 assert 语句中的错误消息将作为参数传递给异常参数`msg`，使用`as`关键字。

因此，assert 语句通常应该用于防止可能的错误，并指定适当的错误消息。****